package tests;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Driver;
import java.util.logging.Logger;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import pages.CRM_CampaignsPage;
import utils.FileUtils;

import listeners.ListenersCRM;

@Listeners(ListenersCRM.class)
public class CRM_CampaignTest  extends BaseTest {
	
	//CRM_CampaignsPage cp = new CRM_CampaignsPage(driver);
	
	/*@BeforeMethod
	public void PreCondition() {
		if(ca) {
		driver = Crm_BaseTest.getDriver("chrome");
		Logger.error("BaseTest:PreCondition:Opening Page");
		}
	}*/
	

	@Test
    public void TC_1_VerifyID_Autogenerated() throws FileNotFoundException, IOException {
    	
    	WebDriver driver = getBrowser();
    	CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
    	CP.VerifyID_Autogenerated(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),FileUtils.readCampaignPropertiesFile("size"));
    }
    
    public void TC_2_Verify_Campainname_mandatory() {
    	
    }
    
    public void TC_3_Verify_Targetsize_is_greater_than_Zero() {
    	
    }
    
    public void TC_4_Verify_Expected_closedate_format() {
    	
    }
    
    public void TC_5_Verify_Status_optional() {
    	
    }
    
    public void TC_6_Verify_TargerAudience_optional() {}
    
    public void TC_7_Verify_Description_is_Oprional() {} 
    public void TC_8_Verify_SaveCampaign_with_All_Fields() {} 
    public void TC_9_Verify_Edit_Campaign_Name() {} 
    public void TC_10_Verify_Update_Campaign_Status() {}

}
