package tests;

import static org.testng.Assert.fail;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.reflect.Method;
import java.sql.Driver;
import java.util.jar.Attributes.Name;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import pages.CRM_CampaignsPage;
import utils.FileUtils;
import utils.WaitUtils;
import listeners.ListenersCRM;

@Listeners(ListenersCRM.class)
public class Crm_CampaignTest extends BaseTest {
	public static Logger logger = LogManager.getLogger("Crm_CampaignTest");

	/*
	 * @BeforeMethod public void PreCondition() { if(ca) { driver =
	 * Crm_BaseTest.getDriver("chrome");
	 * Logger.error("BaseTest:PreCondition:Opening Page"); } }
	 */

	@Test(enabled = false)
	public void TC_1_VerifyID_Autogenerated(Method name) throws FileNotFoundException, IOException {

		// test = extent.createTest(name.getName());
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.Autogenerated_ID(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("size"));

		// test.pass(name.getName);
	}

	@Test(enabled = false)
	public void TC_2_Verify_CampaignName_mandatory() throws FileNotFoundException, IOException {
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.check_CampainName(FileUtils.readCampaignPropertiesFile("size"));

	}

	@Test(enabled = false)
	public void TC_3_Verify_Targetsize_is_greater_than_Zero() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.check_TargetSize_isPositive(FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("negative.size"));
	}

	@Test
	public void TC_4_Verify_Expected_closedate_format() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.filling_the_Form(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("status"), FileUtils.readCampaignPropertiesFile("size"),
				FileUtils.readCampaignPropertiesFile("valid.date"), FileUtils.readCampaignPropertiesFile("audience"),
				FileUtils.readCampaignPropertiesFile("description"));
		System.out.println(" Valid date is accepted!");

		CP.filling_the_Form(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("status"), FileUtils.readCampaignPropertiesFile("size"),
				FileUtils.readCampaignPropertiesFile("invalid.date"), FileUtils.readCampaignPropertiesFile("audience"),
				FileUtils.readCampaignPropertiesFile("description"));
		System.out.println(" Invalid date is not accepted!");
	}

	@Test(enabled = false)
	public void TC_5_Verify_Status_optional() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.Check_Status_optional(FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("size"));
	}

	@Test(enabled = false)
	public void TC_6_Verify_TargerAudience_optional() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.Check_TargerAudience_optional(FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("size"));
	}

	@Test(enabled = false)
	public void TC_7_Verify_Description_is_Oprional() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.check_Description_is_Oprional(FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("size"));
	}

	@Test(enabled = false)
	public void TC_8_Verify_SaveCampaign_with_All_Fields() throws FileNotFoundException, IOException {
		// test = extent.createTest(Name.getName());
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.filling_the_Form(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("status"), FileUtils.readCampaignPropertiesFile("size"),
				FileUtils.readCampaignPropertiesFile("valid.date"), FileUtils.readCampaignPropertiesFile("audience"),
				FileUtils.readCampaignPropertiesFile("description"));
		// test.pass(name.getName);
	}

	@Test(enabled = false)
	public void TC_9_Verify_Edit_Campaign_Name() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.Edit_Campaign_Name(driver, FileUtils.readCampaignPropertiesFile("updated.name"));

	}

	public void TC_10_Verify_Update_Campaign_Status() throws FileNotFoundException, IOException {

		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.filling_the_Form(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("status"), FileUtils.readCampaignPropertiesFile("size"),
				FileUtils.readCampaignPropertiesFile("valid.date"), FileUtils.readCampaignPropertiesFile("audience"),
				FileUtils.readCampaignPropertiesFile("description"));
	}

	@Test(enabled = false)
	public void TC_11_Verify_search_button_Function() throws FileNotFoundException, IOException {
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.select_search_dropdown(driver, FileUtils.readCampaignPropertiesFile("value"),
				FileUtils.readCampaignPropertiesFile("campaign.name"));
	}

	@Test(enabled = false)
	public void TC_12_Verify_Delete_button() throws FileNotFoundException, IOException {
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.filling_the_Form(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("status"), FileUtils.readCampaignPropertiesFile("size"),
				FileUtils.readCampaignPropertiesFile("valid.date"), FileUtils.readCampaignPropertiesFile("audience"),
				FileUtils.readCampaignPropertiesFile("description"));
		CP.select_search_dropdown(driver, FileUtils.readCampaignPropertiesFile("value"),
				FileUtils.readCampaignPropertiesFile("campaign.name"));
		CP.delete_icon.click();
		WaitUtils.waitForElement(driver, CP.Delete_Campaign_Label);
		CP.Delete_Campaign.click();
		CP.Alert_Message();
	}

	@Test(enabled = false)
	public void TC_13_create_duplicate_campaign_name() throws FileNotFoundException, IOException {
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.user_on_campaignPage();
		CP.Enter_CampainName(FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("size"));
		CP.user_on_campaignPage();
		CP.Enter_CampainName(FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("size"));
		CP.select_search_dropdown(driver, FileUtils.readCampaignPropertiesFile("value"),
				FileUtils.readCampaignPropertiesFile("campaign.name"));
		CP.check_appearance_of_element();

	}

}
