package tests;

import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import listeners.ListenersCRM;
import pages.CRM_AddProductPage;
import pages.CRM_ProductsPage;

@Listeners(ListenersCRM.class)
public class Crm_ProductTest extends BaseTest{
	
	@Test
	public void verifyProductIdAutoGeneratedTC_01() throws InterruptedException {
		WebDriver driver = getBrowser(); // getBrowser() method comes from BaseTest,
		// returning the current thread’s WebDriver instance — so you don’t need to
		// initialize it here.
		CRM_ProductsPage pp = hp.clickProducts();
		String actualProductsHeader=pp.getTextFromElement();
		System.out.println("the Products Page Header is: " + actualProductsHeader);
		Assert.assertEquals(actualProductsHeader, "Products");
		CRM_AddProductPage ad=hp.clickAddProduct();
		String actualAddProductHeader= ad.getTextFromElement();
		System.out.println(actualAddProductHeader);
		Assert.assertEquals(actualAddProductHeader, "Add Product");
		String txtbxActualValue=ad.verifyValueFromTextBox();
		String expectedValue = "Auto Generated";
		if(txtbxActualValue.equals(expectedValue)) {
			System.out.println("Test case is Passed");
		}
		else {
			System.out.println("Test case is Failed");
		}
	}
	


}
