package tests;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Driver;
import java.util.jar.Attributes.Name;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import pages.CRM_CampaignsPage;
import utils.FileUtils;

import listeners.ListenersCRM;

@Listeners(ListenersCRM.class)
public class Crm_CampaignTest extends BaseTest {
	public static Logger logger = LogManager.getLogger("Crm_CampaignTest");

	// CRM_CampaignsPage cp = new CRM_CampaignsPage(driver);

	/*
	 * @BeforeMethod public void PreCondition() { if(ca) { driver =
	 * Crm_BaseTest.getDriver("chrome");
	 * Logger.error("BaseTest:PreCondition:Opening Page"); } }
	 */

	@Test
	public void TC_1_VerifyID_Autogenerated() throws FileNotFoundException, IOException {

	   // test = extent.
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.Autogenerated_ID(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				 FileUtils.readCampaignPropertiesFile("size"));
				
		//test.pass(name.getName);	
	}

	public void TC_2_Verify_CampaignName_mandatory() {

	}

	public void TC_3_Verify_Targetsize_is_greater_than_Zero() {

	}

	public void TC_4_Verify_Expected_closedate_format() {

	}

	public void TC_5_Verify_Status_optional() {

	}

	public void TC_6_Verify_TargerAudience_optional() {
	}

	public void TC_7_Verify_Description_is_Oprional() {
	}

	@Test (enabled=false)
	public void TC_8_Verify_SaveCampaign_with_All_Fields() throws FileNotFoundException, IOException {
		// test = extent.createTest(Name.getName());
		WebDriver driver = getBrowser();
		CRM_CampaignsPage CP = new CRM_CampaignsPage(driver);
		CP.filling_the_Form(driver, FileUtils.readCampaignPropertiesFile("campaign.name"),
				FileUtils.readCampaignPropertiesFile("status"), FileUtils.readCampaignPropertiesFile("size"),
				FileUtils.readCampaignPropertiesFile("audience"), FileUtils.readCampaignPropertiesFile("description"));
		//test.pass(name.getName);
	}

	public void TC_9_Verify_Edit_Campaign_Name() {
	}

	public void TC_10_Verify_Update_Campaign_Status() {
	}

}
