package pages;

import org.openqa.selenium.WebDriver;
import java.io.File;
import java.io.IOException;
import java.security.PublicKey;
import java.util.List;
import java.util.Set;

import org.apache.xmlbeans.impl.xb.xsdschema.Public;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;

import constants.FileConstants;
import utils.CommonUtils;
import utils.FileUtils;
import utils.WaitUtils;

public class CRM_CampaignsPage extends BasePage {

	// Constructor
	public CRM_CampaignsPage(WebDriver driver) {
		super(driver);
	}

	@FindBy(xpath = "//b[text()='Campaigns']")
	public WebElement Campaign_label;

	@FindBy(xpath = "//a[text()='Campaigns']")
	public WebElement Campaign_Button;

	@FindBy(xpath = "//button[contains(@class,'btn')]")                                 //"//button[contains(@class,'btn') and contains(@class,'btn-info')]")                                 //"//span[text()='Create Campaign']")
	public WebElement Campaign_Form_button;

	@FindBy(xpath = "//div[@class='form-wrapper']/h3[1]")
	public WebElement Create_Campaign_Label;

	@FindBy(xpath = "//div[@class='form-group']/input[@name='campaignId']")             //"//input[@name='campaignId]")
	public WebElement Autogenerated_id_inputBox;

	@FindBy(xpath = "//tr[@class='tr']/td[1]")
	public WebElement Auto_Campaign_id;

	@FindBy(xpath = "//tr[@class='tr']/td[5]")
	public WebElement Auto_Target_size;

	@FindBy(xpath = "//div[@class='form-group']/input[@name='campaignName']")      //"//input[@name='campaignName]")
	public WebElement Campaign_Name;

	@FindBy(xpath = "//tr[@class='tr']/td[2])")
	public WebElement Auto_Name;

	@FindBy(xpath = "//input[@name='campaignStatus]")
	public WebElement Campaign_Status;

	@FindBy(xpath = "//div[@class='form-group']/input[@name='targetSize']")                                //"//input[@name='targetSize]")
	public WebElement campaignSize;

	@FindBy(xpath = "//input[@name='targetAudience]")
	public WebElement targetAudience;

	@FindBy(xpath = "//textarea[@name='description']")
	public WebElement Description;

	@FindBy(xpath = "//button[@type='submit']")
	public WebElement Submit_button;

	@FindBy(xpath = "//table [contains (@class,'table table-striped table-hover')]")
	public List<WebElement> Table_contents;

	@FindBy(xpath = "//input[@class='btn btn-default']")
	public List<WebElement> DeleteCampaign_Cancel;

	@FindBy(xpath = "//input[@class='btn btn-danger']")
	public List<WebElement> Delete_Campaign;

	@FindBy(xpath = "//*[text()='Delete Campaign']")
	public List<WebElement> Delete_Campaign_Label;

	// <div role="alert" class="Toastify__toast-body">AI Campaign Campaign
	// Successfully Deleted </div>
	public void filling_the_Form(WebDriver driver, String name, String status, int Asize, String audience,
			String descr) {

		if (Campaign_label.isDisplayed()) {
			System.out.println("you are on 1 Campaign Page");
			Campaign_Button.click();

			if (WaitUtils.waitForElement(driver, Campaign_Name)) {
				// Autogenerated_id_inputBox.sendKeys("");
				Campaign_Name.sendKeys(name);
				Campaign_Status.sendKeys(status);
				campaignSize.sendKeys(String.valueOf(Asize));
				targetAudience.sendKeys(audience);
				Description.sendKeys();
				Submit_button.submit();
				Alert alert = driver.switchTo().alert();
				String alert_msg = alert.getText();
				System.out.println(" Alert message: " + alert_msg);
				// if(WaitUtils.waitForElement (driver,alert)) {

				// else System.out.println(" Please click Create Campaign Button ");
			} else
				System.out.println(" Check again if you are on Campaign form page");

		}
	}

	public boolean VerifyID_Autogenerated(WebDriver driver, String name, String Asize)  {
		boolean autogenerate_id = false;
		driver.manage().window().maximize();
		if (WaitUtils.waitForElement(driver, Campaign_label)) {
			System.out.println("you are on 2 Campaign Page");
			WaitUtils.waitForElement(driver,Campaign_Form_button );
			Campaign_Form_button.click();
			System.out.println(" Campaign_Form_button is clicked");

			
			if (WaitUtils.waitForElement(driver, Autogenerated_id_inputBox))
				//Autogenerated_id_inputBox.sendKeys("");
			Campaign_Name.sendKeys(name);
			System.out.println(" Name entered");
			String AT_size = String.valueOf(Asize);
			campaignSize.sendKeys(AT_size);
			Submit_button.click();
			System.out.println(" You clicked submit button");
			if (WaitUtils.waitForElement(driver, Campaign_label)) {
				// int num = String.valueOf(AT_size);
				String N = Auto_Name.getText();

				System.out.println(" Actual Target Size: " + AT_size + " Expected Target size: " + Asize);
				System.out.println(" Actual Campaign Name: " + N + " Expected name: " + name);
			}
			if (Auto_Campaign_id.equals(AT_size)) {
				System.out.println(" Automatic ID generated");
				autogenerate_id = true;
			}
		}
		return autogenerate_id;
	}

	public void Verify_Campain_name_mandatory() {

	}

	public void Verify_Targetsize_is_greater_than_Zero() {

	}

	public void Verify_Expected_closedate_format() {

	}

	public void Verify_Status_optional() {

	}

	public void Verify_TargerAudience_optional() {
	}

	public void Verify_Description_is_Oprional() {
	}

	public void Verify_SaveCampaign_with_All_Fields() {
	}

	public void Verify_Edit_Campaign_Name() {
	}

	public void Verify_Update_Campaign_Status() {
	}
}
